sudo: required
language: python
python:
  - "3.6"
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:

script:
  #- yarn test
  #- yarn build
  # build docker images
  - docker build -t chotube-auth-server .
  - docker tag chotube-auth-server registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script: 
    # push to dockerhub & heroku
    docker push santiagomariani/chotube-auth-server;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master