version: "3"

services:
    auth-server:
        container_name: chotuve_auth-server
        depends_on:
        - db
        build: 
            context: .
            dockerfile: Dockerfile.development
        restart: always
        ports:
        - "4000:5000" 
        volumes:
        - ./:/app
        env_file:
            - ./.env.dev
    db:
        image: postgres:12-alpine
        volumes:
        - ./postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=chotuve
        - POSTGRES_PASSWORD=chotuve
        - POSTGRES_DB=chotuve_auth_server