version: "3"

services:
    auth-server:
        container_name: chotuve_auth-server
        build: 
            context: .
            dockerfile: Dockerfile.development
        restart: always
        ports:
        - "4000:5000" 
        volumes:
        - ./:/app
