# base image with python 3
FROM python:3.8.1-slim-buster
WORKDIR /app

# install netcat to wait database server to start
RUN apt-get update && apt-get install -y netcat

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY ./docker-entrypoint-dev.sh .

ENTRYPOINT ["sh", "/app/docker-entrypoint-dev.sh"]





