# base image with python 3
FROM python:3

WORKDIR /app

COPY ./requirements.txt .

RUN pip install -r requirements.txt

# flask envs
ENV FLASK_APP=api.py
ENV FLASK_ENV=development

COPY docker-entrypoint.sh /

ENTRYPOINT ["sh", "/docker-entrypoint.sh"]





